### ISSUE TITLE
Some diacritic version glyphs doesn't show up. Shows base glyph instead.

### ISSUE THREAD

**Issue by tderkert** [carrois/Kernkraft#7]
I'm in the middle of kerning a typeface and Kernkraft has been working great until now. As I was about to kern /S it stopped showing diacritic versions of some glyphs, instead it shows the same base glyph multiple times. This happens to some letters(A,H,Y,Z,i etc.) but not to others(C,K, L etc.). I have no checkboxes checked in the plugin settings.

I get this: 
![image](https://cloud.githubusercontent.com/assets/6050484/17276697/1a87b128-5731-11e6-81de-d283cb6e035c.png)
![image](https://cloud.githubusercontent.com/assets/6050484/17276746/41de1c52-5732-11e6-9a91-4630d1313b25.png)

Instead of this (manually edited): 
![image](https://cloud.githubusercontent.com/assets/6050484/17275959/2b763f02-571a-11e6-9c3a-b2c614fd5bfe.png)
![image](https://cloud.githubusercontent.com/assets/6050484/17276748/8b61c130-5732-11e6-9e06-e96c1f9027cf.png)

Glyphs (Cutting Edge versions): Version 2.3.1 (911)
I have been working on this version for a while and it was working fine but suddenly did what i described above.

Appreciate the plugin a lot. Makes kerning a slightly less daunting task. Thanks!

**Comment by Mark2Mark** [comment]
Hi, thank you very much for reporting. I recently changed a little thing and did not test it against this particular issue (Testing each improvement is actually the hardest thing with this complex tool).

I removed the additional feature temporarily in order to test it with a non-public version. Please check if it helped and let me know. The plugin should update itself after a Glyphs restart if you installed it via the Plugin Manager.

Kernkraft Version 1.9.1

**Comment by tderkert** [comment]
Hi, thanks for the quick reply and action. I tried to install it from scratch at work(didn't have it installed here) but now I can't see it under 'Glyph' menu item at all. I'll check when I get home to see if it is the same there. 

By the way, should the plugin update itself automatically? Seems like these kinds of problems could possibly be avoided, or at least make more sense to the user why and when the problem appear. I guess that is a Glyphs issue if is the case.

Again, thanks for making this awesome tool.

**Comment by Mark2Mark** [comment]
Fixed another thing. The new function (which is not bothering you in this case) now only applies if `Skip Group Members` and `Skip Components` are active in the UI.

If you got the checkboxes unchecked, it should display your desired strings. Can you please check again?

Yes, the plugin should update automatically. Sometimes it doesn’t. If so, please go to the Glyphs Plugins folder. Next to it should be a folder called `Repositories`. You can delete the `Kernkraft` folder and reinstall it via the Plugin Manager. ( @schriftgestalt )

**Comment by tderkert** [comment]
Tried deleting it from Repositories and Plugins, and installed again. It still won't appear for me.

This is where it should appear, if I remember correctly:
![image](https://cloud.githubusercontent.com/assets/6050484/17289634/d6ab3484-57da-11e6-96bf-ddaa0b45c39c.png)

Does it work fine for you?

**Comment by Mark2Mark** [comment]
It works for me. Could you please do me a favour and right click onto `Kernkraft.glyphsPlugin` in the `Repositories > Kernkraft` folder. In the context menu click `Show Package Contents` and in there navigate to `Contents > Resources > KernKraftModule.py`. Open this file in the Text editor and check the first few lines.
Lines 12–17 should be:

```
# Changelog:
#   1.9
#       + Use Glyph with Group-Name if given (instead of first Group Member) [only if BOTH sides KG are the same]


import os
```

And line 51 should be:
`version = "1.9.1"`

**Comment by tderkert** [comment]
Sure. It appears to be correct. 

Line 12-17:

```
# Changelog:
#   1.9
#       + Use Glyph with Group-Name if given (instead of first Group Member) [only if BOTH sides KG are the same]


import os
```

Line 51: 
`version = "1.9.1"`

Is there something else that could come into play, like my OS version?
I'm not at my regular font work computer so I'll check how it works later to night at my other computer as well.

**Comment by Mark2Mark** [comment]
I am not sure. The update seems to have worked on your machine. I use the same Glyphs Version. Do you have vanilla installed? Glyphs Preferences > Addons > Install Modules.

Otherwise we might need to wait to check it on your other computer.

**Comment by schriftgestalt** [comment]
Can you check the console.app and the macro panel if you fine an error message?

**Comment by tderkert** [comment]
@Mark2Mark No it seems like I hadn't. I installed it and now it works. Thanks! 
I probably did install at home at some point, hence it was working there before this issue.

I don't get any feedback that I have installed it or anything, but it worked afterwards so I'm assuming that it did it successfully.

**Comment by tderkert** [comment]
@schriftgestalt Checked after I installed Vanilla and got Kernkraft to work, but I do get an error on Glyphs startup that seems to be related to Vanilla. Not sure if it is relevant anymore though, but here it is:

```
01/08/16 13:07:18,727 Glyphs[906]: Error loading /Library/Python/2.7/site-packages/vanilla/externalFrameworks/RBSplitView/RBSplitView.framework/RBSplitView:  dlopen(/Library/Python/2.7/site-packages/vanilla/externalFrameworks/RBSplitView/RBSplitView.framework/RBSplitView, 265): no suitable image found.  Did find:
    /Library/Python/2.7/site-packages/vanilla/externalFrameworks/RBSplitView/RBSplitView.framework/RBSplitView: file too short
```

**Comment by schriftgestalt** [comment]
You can ignore this error.

**Comment by Mark2Mark** [comment]
If it now shows your diacritic glyphs when both mentioned checkboxes are unchecked, I can close this issue. Thanks for keeping up.

**Comment by tderkert** [comment]
Yes, I can confirm that it works, both unchecked. Thanks for fixing it.

**Comment by tderkert** [comment]
Hi. This bug seems to be back again.

**Comment by Mark2Mark** [comment]
I cannot reproduce it. Can you please specify? What version of Kernkraft, and what is your Window looking like? Perhaps a screenshot may help me.

Or is the plugin not showing in the menu?

**Comment by tderkert** [comment]
Yeah sure. Here's a screenshot. Version 1.9 (Beta)
![image](https://cloud.githubusercontent.com/assets/6050484/17406808/4566d8ce-5a65-11e6-94ee-871af3c807eb.png)

**Comment by Mark2Mark** [comment]
This is weird. It’s a pretty obsolete version. It should have `Kernkraft 1.9.4 (beta)` written in the Menu Title.

**Comment by tderkert** [comment]
Ok, I'll try to uninstall it and delete. Should probably have tried that before.
But it's a little bit strange since it was working before.

**Comment by tderkert** [comment]
...and that solved to problem. I'll try that next time instead. Thanks!

**Comment by Mark2Mark** [comment]
Thanks for the answer. I wonder why it was downgraded, since you already had the 1.9.1. Maybe this was on the other computer?

**Comment by tderkert** [comment]
Now that you say that is actually a possibility. Didn't think about it as paused the kerning for a while and went on a little glyph designing spree. So that is probably the explanation. 
My bad. Thanks!
